---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 130.193.55.36
    jenkins-agent-01:
      ansible_host: 178.154.193.245
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: evgen